### ISSUE TITLE
new version disabled by Chrome

### ISSUE THREAD

**Issue by nikosvaggalis** [foxyproxy/browser-extension#113]
The new update was automatically disabled by Chrome because the extension needs more permissions such as 
"read and change your data on all websites", cookies etc.What does that mean and what has changed from the previous version which did not ask for those permissions?

**Comment by erosman** [comment]
> The new update was automatically disabled by Chrome ...

New version is not disabled on Chrome. The last version uploaded to Chrome was 8.2.
Version 8.8 will be uploaded to Chrome soon.

> What does that mean and what has changed from the previous version which did not ask for those permissions?

Permissions are explained in the README on the [front repo page](https://github.com/foxyproxy/browser-extension).

**Comment by nikosvaggalis** [comment]
This is what a get
![foxy](https://github.com/foxyproxy/browser-extension/assets/26706920/2ea2f871-e74d-467c-bdb9-4408854b3b96)

**Comment by erosman** [comment]
These permissions have been present in FoxyProxy v6-7 on Firefox. However, on Chrome, FoxyProxy was still v3 and v3 didn't have the features that required these permissions.

### Read and change all your data on all websites
Any extension that has `<all_urls>` permission will result in the above warning. In itself, it doesn't mean a lot since extensions often need additional permission for the API that is going to use `<all_urls>`. In FoxyProxy's case, it is needed in order to supply credentials for [Proxy authorization](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired#proxy_authorization).

### Display notifications
That is a really harmless permission and should not require a warning (it doesn't on Firefox IIRC).

### Manage your downloads
Required to export the extension settings to a file. Users can import that file to other Chrome/Firefox instances, or share it with colleagues, in order to keep the same settings. It can also be backed up and used later.
