### ISSUE TITLE
External IP/Location functionality

### ISSUE THREAD

**Issue by TriMoon** [foxyproxy/browser-extension#6]
Could you please drop all code related to this functionality please?
IMHO: It has no place in an extension used for proxy configurations, and only serves to spy on users to provide adverts etc.

If a user wants to know it's own external IP there are many other ways instead of backing it into an extension whos main purpose is not related to that.

**Comment by erosman** [comment]
The functionality is not automatic. It only runs if user decides to run it by clicking the button. Therefore, it is users' choice to use it or not.

**Comment by TriMoon** [comment]
That kind of privacy breaching functionality always starts like that, until it is used behind the scenes without user's content.
Just get rid of the bloat and make the extension even smaller :wink:

**Comment by erosman** [comment]
It can be removed if there is a popular demand for it.

There are users who might prefer to utilise such functions from a trusted developer rather than a 3rd party. Furthermore, in case of `Get Location`, when there are 10s of proxies, getting, IP, City, Country, Continent for each and entering them one by one, may prove to be a cumbersome task.

FoxyProxy's code is open source and clear (not obfuscated or minified). Users are free to inspect the code if they have any concerns.

Please also note that there are many FoxyProxy account holders who already use these services and/or features.

**Comment by TriMoon** [comment]
> There are users who might prefer to utilise such functions from a trusted developer rather than a 3rd party.

Then please make the service address used for fetching the IP configurable by the user, so we won't be forced to use yours...
(and thus eliminate the possibility for spying)

**Comment by ericjung** [comment]
This is an optional feature that only engages if the user proactively clicks a button. It has existed for many years in FoxyProxy.

> To make it clear don't hardcode the address in the source code ([example](https://github.com/foxyproxy/browser-extension/blob/main/src/content/background.js#L130)), just make it a default in the config...

What config? How do you suggest to make this configurable given your other comment:

> This kind of arguments are useless, because being able to inspect the code does not equal ability to change it from a user's pov.

If you have a good suggestion how to expose the URL so users can change it, we can discuss it. To be clear, this feature will not be removed. We will entertain ideas on how to make it configurable, and that is all.

**Comment by TriMoon** [comment]
You made your point of not willing to remove spy possibilities in your software, and i made clear from a users point of view why you should.
You asking how to make it configurable is just trying to talk in circles which i don't have time to spend in...
You have many options that users can configure in your UI, add one for this, simple...

/dropping participation in this issue, have fun and a nice day.

**Comment by ericjung** [comment]
You are free not to use the feature. Then there is no risk of spying. And if you do use the feature, the most spying that can be done is that the web servers behind https://getfoxyproxy.org/geoip/?raw=1 can see and store your proxy server's IP address.

For the record, I am responsible for those web servers. I am going on the record right now to say that those web servers never have and never will store or use those IP addresses -- or any other info from FoxyProxy browser extension users -- in any way. But you don't have to take my word for it. Just don't use the feature.

You can see a similar commitment at https://getfoxyproxy.org right now: there are no trackers, no analytics (google or otherwise), no advertising. Even the CAPTCHA that we use at https://getfoxyproxy.org/order is a self-hosted CAPTCHA image -- not reCAPTCHA or hCAPTCHA or anything else (you have to click one of the payment methods to see the CAPTCHA). We do not use a CDN because we don't want you to be tracked by CloudFlare or another CDN when visiting our website; everything is self-hosted.

**I ask you to load https://getfoxyproxy.org/, https://getfoxyproxy.org/order/, and any other page at our site with uBlock Origin turned on. You will see NOTHING blocked. ZERO.**

That's very deliberate and intentional.
