### ISSUE TITLE
Difference between standard and basic

### ISSUE THREAD

**Issue by Doc73** [foxyproxy/browser-extension#81]
Could you please better document the difference between the standard and basic versions?

Currently, in fact, I can't notice any difference. :smile: 

Thank you very much in advance and congratulations for this exceptional tool that I have been using for I don't know how many years now.

Doc

**Comment by erosman** [comment]
> Could you please better document the difference between the standard and basic versions?

None in v8+ :smile: 

Originally, Basic had the same code as Standard but the pattern related features were disabled.

FoxyProxy 8 uses a unified code for Standard & Basic, on both Firefox & Chrome.
The unified code enables users to freely share (import/export) settings between the versions.
In future, it may be decided to "hide"  pattern related features on FoxyProxy Basic (nothing decided yet).

For the time being, users can use either, and bearing in mind the AMO review process, the latest version is available immediately as FoxyProxy Basic but takes some days for FoxyProxy (standard).

**Comment by Doc73** [comment]
Yes, I knew this for the old version, but I thought there were plans for that for the new one too.
In short, for now we can say that the basic is more of a sort of beta.

Thanks for the clarifications and good work!

**Comment by erosman** [comment]
### Version 8.8

- Updated user interface to hide patterns on FoxyProxy Basic

Since v8.8, the UI is slightly different in FoxyProxy Basic and the pattern related features are hidden.
However, the functionality is still the same and settings from Standard can be used in Basic and vice versa.
There is also a new feature in 8.8 to temporary unhide the hidden.
