### ISSUE TITLE
DSN resolution no longer working with SOCKS5

### ISSUE THREAD

**Issue by xwitty** [foxyproxy/browser-extension#97]
a host - not allowed with my local proxy - is accessible with a SOCKS5-proxy in v7.5.1, but not v8.6

as far as I can say, the DSN-resolution is already blocked, before switching out to the proxy.

**Comment by erosman** [comment]
Have you tried Proxy DNS?

BTW, Proxy DNS (was global in v8.6) is moved to per-server in v8.7.

**Comment by evetsso** [comment]
I think I ran into the same problem - it seems that a recent update to the extension broke DNS resolution through SOCKS5 for an existing proxy.  The proxy I have defined appears to have Proxy DNS enabled when I look at its configuration (presumably this setting was migrated from the previously-global setting).

I am able to work around the problem by disabling Proxy DNS, saving the proxy configuration, re-enabling Proxy DNS, and saving the config again.

**Comment by erosman** [comment]
> The proxy I have defined appears to have Proxy DNS enabled 

Actually, the enabled state is a preset.

> I am able to work around the problem by disabling Proxy DNS, saving the proxy configuration, re-enabling Proxy DNS, and saving the config again.

The data is migrated from global to individual proxies per request in #75.

However, the Firefox proxying request process in FoxyProxy is refreshed on browser restart, extension re-enable, background script reload (MV3), and edits in the Options page.
It SHOULD also happen when an extension is upgraded BUT I have seen instances that due to caching by the browser, the extension might not be fully restarted during an upgrade.

I am guessing that for users who keep their browser on all the time, most of those cases wont happen until an edit is made in the Options page (any edit will do).

**Comment by erosman** [comment]
Are you still experiencing the issue?

**Comment by GlenDC** [comment]
I can confirm the bug is still there.
https://github.com/foxyproxy/browser-extension/issues/97#issuecomment-1866471925 this resolves it.
But not very UX if it has to happen fequently. Either way that makes it work.

**Comment by erosman** [comment]
Can you provide an STR (steps to reproduce) so that I can see what is happening?
When I try, I don't experience the issue.

**Comment by Francewhoa** [comment]
Related challenge with steps to reproduce and screenshots at https://github.com/foxyproxy/browser-extension/issues/166
